### ISSUE TITLE
Use with max MAX13487 

### ISSUE THREAD

**Issue by gfucka** [jrbenito/ABBAurora#11]
Hi,
I would like to use it with MAX13487 who doesn't have the direction pin (RE/DE). how can I do?

Thank you

**Comment by jrbenito** [comment]
@gfucka 

I never used the MAX13487 and I don't have a test rig to run tests on it now. Maybe conditionally apply the direction pin logic. For instance, create a macro to specify when it the TX pin necessary and wrap all the logic for dealing with that pin the code would work. (educated guess based on a quick glance at the datasheet)

If you implement it I will gladly merge the PR, however I don't have the environment with an Aurora inverter to test this anymore, hence I cannot do it on my side.

Also, if anyone wants to assume this code I can add this person as contributor with full access or even transfer the ownership of the repository. Since I moved home/work/country I have zero access to system where I can test/develop this.

Thanks for your interest in this code.
